on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven
    - name: Step 2 - Build with Maven
      run: mvn -B package --file pom.xml
    - name: Step 3 - Clean and Package with Maven
      run: mvn clean package --file pom.xml
    - name: Step 4 - Push to deploy
      uses: actions/github-script@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b deploy
          git add .
          git commit -m "Automated Deployment"
          git push -f origin deploy
