on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven
    - name: Step 2 - Build with Maven
      run: mvn -B package --file pom.xml
    - name: Step 3 - Clean and Package with Maven
      run: mvn clean package --file pom.xml
    - name: Check files generated
      run: |
        ls -l target
        echo "List of files in target directory"
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: deployawslambda
      run: |
        aws lambda update-function-code --function-name=Stocktesting --zip-file=fileb://./target/ServerlessProject-0.0.1-SNAPSHOT-aws.jar
    - name: Push to deploy
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b deploy
        git add -f ./target/*
        git commit -m "Automated Deployment"
        git push -f origin deploy
